version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sky_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - '5432'
    ports:
      - '5432:5432'

  django:
    container_name: sky_django
    build:
      context: .
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             exec gunicorn core.wsgi:application -b 0.0.0.0:8000 --reload"
    expose:
      - 8000
    ports:
      - '8001:8000'
    restart: always
    env_file:
      - .env_dist
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - django
      - redis

  celery_beat:
    build: .
    command: celery -A core beat -l INFO
    depends_on:
      - celery_worker
      - django
      - redis