# Generated by Django 4.2.4 on 2023-08-22 08:26

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("result", models.JSONField(verbose_name="Результат проверки")),
                (
                    "verification_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        default=False, verbose_name="Письмо отправлено пользователю"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Поддерживаемый формат: .py",
                        upload_to=files.models.rename_file,
                        validators=[
                            django.core.validators.FileExtensionValidator(["py"])
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=64, verbose_name="Название файла"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("overwritten", "Перезаписан"),
                            ("verified", "Проверен"),
                            ("del", "Удален"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
    ]
