# Generated by Django 4.2.4 on 2023-08-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="filereport",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_reports",
                to="files.fileupload",
                verbose_name="Файл",
            ),
        ),
    ]
